### ISSUE TITLE
SCNRenderer.device

### ISSUE THREAD

**Issue by wvdk** [xmartlabs/MetalPerformanceShadersProxy#9]
First off, super awesome of you guys to make this! 

Adding it to my project and hit a wall when I got to a handful of references to SCNRenderer's device property which is a MTLDevice. Could we stub that as well?

I'd be happy to help out if you point me in the right direction.

(I'm running Xcode 9.4.1)

**Comment by bryant1410** [comment]
@wvdk sorry for the silence. Have you managed to solve it? We haven't had time these days to take a look at it.
